### ISSUE TITLE
No page selected on default

### ISSUE THREAD

**Issue by CubicrootXYZ** [julian-printemps/vue3-pagination#1]
**Describe the bug**

The pagination does not show any page selected on reload. I need to click a number first. 

**Screenshots**

![Unbenannt](https://user-images.githubusercontent.com/24812442/114063521-ff438c80-9898-11eb-9810-53f7a10519b9.PNG)

I'd exepct this on default: 

![Unbenannt2](https://user-images.githubusercontent.com/24812442/114063596-15e9e380-9899-11eb-97ba-d75524144f4a.PNG)

**Desktop (please complete the following information):**

 - Browser: Firefox 87.0

**What I already tried**

I already set modelValue to 1, but that did not fix it: 
```
<v-pagination
    v-model="page"
    :pages="pagination.total_pages"
    :range-size="1"
    modelValue="1"
    active-color="#DCEDFF"
    @update:modelValue="pageUpdate"
/>
```

**Comment by julian-printemps** [comment]
@CubicrootXYZ `modelValue` represent the value of `v-model`.
Try setting `page` to `1` by default.
Also, you don't need to pass the `modelValue` prop.
