### ISSUE TITLE
Disable forcing styles option

### ISSUE THREAD

**Issue by xxSkyy** [julian-printemps/vue3-pagination#3]
It'd be nice if there will be option to disable force inline styles for Page transparency background and for active button and leave just classes for custom styling. 
The best way would be also custom templates to fit your needs.

**Comment by FelipeRiv** [comment]
Hi!
Did you find any way to pass custom styles o classes to use bootstrap o anything like that?

**Comment by xxSkyy** [comment]
@FelipeRiv no, I just styled these classes.
